# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computação Quântica com Ket
author: Evandro Chagas Ribeiro da Rosa
copyright: "2024"
logo: gcq.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/evandro-crr/ket-book  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false

launch_buttons:
  notebook_interface        : jupyterlab 
  thebe                     : true 
  binderhub_url             : "https://mybinder.org"
  colab_url                 : "https://colab.research.google.com" 

sphinx:
  config:
    language: "pt_BR"
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    intersphinx_mapping:
      python:
      - https://docs.python.org/pt-br/3.10
      - null
      ket:
      - https://quantumket.org
      - null
    suppress_warnings: ["mystnb.unknown_mime_type"]